# Generated by Django 6.0.2 on 2026-02-07 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dostawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dostawca', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=50)),
                ('ilosc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=50)),
                ('rozmiar', models.CharField(max_length=20)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produkcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ilosc', models.IntegerField()),
                ('partia', models.CharField(max_length=50)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField(default=0)),
                ('ostatnia_aktualizacja', models.DateTimeField(auto_now=True)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient', models.CharField(max_length=100)),
                ('ilosc', models.IntegerField()),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='oczekuje', max_length=20)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.produkt')),
            ],
        ),
    ]
